name: Download data

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 1 * * *'   # 1 AM UTC
  #   - cron: '0 3 * * *'   # 3 AM UTC
  #   - cron: '0 6 * * *'   # 6 AM UTC
  #   - cron: '0 9 * * *'   # 9 AM UTC
  #   - cron: '0 12 * * *'  # 12 PM UTC
  #   - cron: '0 15 * * *'  # 3 PM UTC
  #   - cron: '0 18 * * *'  # 6 PM UTC
  #   - cron: '0 21 * * *'  # 9 PM UTC


jobs:
  download_data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: List files
        run: |
          ls -ltran                                                                                                                                                                                             
          
      - name: Download_data-futures
        env:
          FREQTRADE__EXCHANGE__API_KEY: ${{ secrets.FREQTRADE__EXCHANGE__API_KEY }}
          FREQTRADE__EXCHANGE__SECRET: ${{ secrets.FREQTRADE__EXCHANGE__SECRET }}
          FREQTRADE__EXCHANGE__ACCOUNT_ID: ${{ secrets.FREQTRADE__EXCHANGE__ACCOUNT_ID }}
          HTTPS_PROXY: ${{ secrets.HTTPS_PROXY }}
        run: |
          docker run --rm \
          -e FREQTRADE__EXCHANGE__API_KEY \
          -e FREQTRADE__EXCHANGE__SECRET \
          -e FREQTRADE__EXCHANGE__ACCOUNT_ID \
          -e HTTPS_PROXY \
          --mount type=bind,source=$(pwd)/user_data,target=/freqtrade/user_data/ \
          trmaphi/freqtrade:8054f47b \
          download-data \
          --exchange itlx \
          --trading-mode futures \
          --pairs=".*" \
          --timeframes 1m 5m 15m 30m 1h 1d 1w 1M \
          --datadir="/freqtrade/user_data/data/orderly" \
          --new-pairs-days 365 \
          --config=/freqtrade/user_data/config.json 2>&1 | tee download_data_logs_futures.txt

      - name: Fix permissions before commit
        run: |
          sudo chown -R $(id -u):$(id -g) .

      - name: Commit report
        run: |
          git config --global user.name 'trmaphi'
          git config --global user.email 'trmaphi@users.noreply.github.com'
          git add .
          git commit -m "Data update orderly"
          git push
